spring.application.name=smart-campus



# =============================================
# Server
# =============================================
server.port=${SERVER_PORT:8080}

# =============================================
# Spring Security
# =============================================
spring.security.user.name=${SECURITY_USER_NAME:admin}
spring.security.user.password=${SECURITY_USER_PASSWORD:admin123}

