spring.application.name=smart-campus


# =============================================
# Server
# =============================================
server.port=${SERVER_PORT:8080}

# =============================================
# Google OAuth2 Login Config

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# =============================================
# MongoDB - Use environment variable or fallback to default
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://admin:12345@smartcampus.ozevafw.mongodb.net/smartcampus?retryWrites=true&w=majority&connectTimeoutMS=10000&socketTimeoutMS=10000&serverSelectionTimeoutMS=10000}
# =============================================
# Multipart Config (File Uploads)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
