spring.application.name=smart-campus


# =============================================
# Server
# =============================================
server.port=${SERVER_PORT:8080}

# =============================================
# Spring Security
# =============================================
spring.security.user.name=${SECURITY_USER_NAME:admin}
spring.security.user.password=${SECURITY_USER_PASSWORD:admin123}

# =============================================
# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:12345@smartcampus.ozevafw.mongodb.net/smartcampus?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://admin:12345@smartcampus.ozevafw.mongodb.net/smartcampus?retryWrites=true&w=majority
spring.data.mongodb.host=
spring.data.mongodb.port=
